name: Auth Service CI/CD

on:
  push:
    branches: [ main ]

jobs:
  ci-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Docker image
        run: |
          docker build \
            --build-arg DB_URL="${{ secrets.DB_URL }}" \
            --build-arg USER_POOL_ID=${{ secrets.USER_POOL_ID }} \
            --build-arg CLIENT_ID=${{ secrets.CLIENT_ID }} \
            --build-arg REGION=${{ secrets.REGION }} \
            -t ${{ secrets.DOCKER_HUB_USERNAME }}/auth-service:latest .

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/auth-service:latest

  cd-deploy:
    needs: ci-build
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ap-southeast-1

      - name: Update Task Definition Image
        id: taskdef
        run: |
          TASK_FAMILY="auth-service"
          IMAGE="${{ secrets.DOCKER_HUB_USERNAME }}/auth-service:latest"

          echo "Loading current task definition..."
          aws ecs describe-task-definition --task-definition $TASK_FAMILY \
            | jq --arg IMAGE "$IMAGE" '.taskDefinition | .containerDefinitions[0].image = $IMAGE' \
            > new-taskdef.json

          echo "Registering new task definition..."
          NEW_REVISION=$(aws ecs register-task-definition \
            --cli-input-json file://new-taskdef.json \
            --query 'taskDefinition.taskDefinitionArn' \
            --output text)

          echo "new_revision=$NEW_REVISION" >> $GITHUB_OUTPUT

      - name: Deploy new ECS revision
        run: |
          echo "Deploying new revision..."
          aws ecs update-service \
            --cluster microservices-cluster \
            --service auth-service \
            --task-definition ${{ steps.taskdef.outputs.new_revision }} \
            --force-new-deployment

          echo "Deployment started!"
